## Skeleton taken from Chirp project
name: build_and_test
on: 
  workflow_call: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.*
    - name: Restore functionTests dependencies
      run: dotnet restore Tests/Function.Tests
    - name: Build_function_tests
      run: dotnet build Tests/Function.Tests --no-restore
    - name: Test_function_tests
      run: dotnet test Tests/Function.Tests --no-build --verbosity normal
      
    - name: Restore UITests dependencies
      run: dotnet restore Tests/PlaywrightTests
    - name: Build_ui_tests
      run: dotnet build Tests/PlaywrightTests --no-restore
    - name: Test_ui_tests
      run: dotnet test Tests/PlaywrightTests --no-build --verbosity normal

    