## Skeleton taken from Chirp project
name: build_and_test
on: 
  workflow_call: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore Function
    - name: Build
      run: dotnet build  Function --no-restore
    - name: Test
      run: dotnet test Tests/Function.Tests --no-build --verbosity normal